[Android_Adreno840 DeviceProfile]
; To get both Frame Gen and Vulkan Toggle, change "Android_High" to "Android_Adreno840"
; Also change the dp.Override in Engine.ini to dp.Override="Android_Adreno840"
DeviceScore=69696
CVars=r.Mobile.EnergySavingFrameInterpolation=0
Cvars=r.Mobile.HighQualityMaterial=1
Cvars=r.Android.DisableVulkanSupport=1
Cvars=r.Android.VulkanSetting=1
Cvars=r.imp.SSMbScaleLod0=0.75
Cvars=r.imp.SSMbScaleLod1=1.75
CVars=wp.Runtime.LoadingRangeScale=0.80
CVars=wp.Runtime.PlannedLoadingRangeScale=1.10
CVars=sg.PostProcessQuality=4
CVars=sg.TextureQuality=3
